services:
  mysql:
    image: mysql:8.4
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mydata:/var/lib/mysql
  redis:
    image: redis:8.2.1
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped

volumes:
  mydata: